"""
agents/report_writer.py — Part 4: Final Pentest Report Writer
Synthesises all 3 pipeline JSON outputs into a professional deliverable.

Run standalone:
  python -m agents.report_writer --recon   reports/recon/recon_*.json
                                 --vulns   reports/vulns/vulns_*.json
                                 --exploits reports/exploits/exploits_*.json

Or via main.py:
  python main.py --target example.com --parts 1,2,3,4
"""

import json
import argparse
import datetime
import time
from pathlib import Path
from dataclasses import asdict

from rich.panel  import Panel
from rich.rule   import Rule
from rich.table  import Table
from rich.syntax import Syntax
from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI
# Lazy import — langchain_google_genai has a version conflict with langchain_core
# It is only imported when LLM_PROVIDER == "gemini"
ChatGoogleGenerativeAI = None

from core.utils  import console, load_json, save_json, save_markdown
from core.config import GROQ_API_KEY, GROQ_MODEL_DEFAULT, GROQ_MODELS, GEMINI_API_KEY, GEMINI_MODEL_DEFAULT, FINAL_DIR, LLM_PROVIDER


# ══════════════════════════════════════════════════════════
#  SECTION PROMPTS
#  Each section is generated by a separate focused LLM call.
#  Smaller prompts → better quality output per section.
# ══════════════════════════════════════════════════════════

def _llm_call(llm: ChatGroq, prompt: str) -> str:
    return llm.invoke(prompt).content.strip()

def _limit_data(data, limit=10):
    """Truncate lists to prevent exceeding LLM token limits."""
    if isinstance(data, list):
        return data[:limit]
    if isinstance(data, dict):
        return {k: _limit_data(v, limit) for k, v in data.items()}
    return data


def section_executive_summary(llm: ChatGroq, target: str,
                               vuln_summary: dict, confirmed_count: int,
                               scan_dates: dict) -> str:
    prompt = f"""You are a senior penetration tester writing the Executive Summary of a professional pentest report.

Target:          {target}
Recon date:      {scan_dates.get('recon','N/A')}
Vuln scan date:  {scan_dates.get('vuln','N/A')}
Exploit date:    {scan_dates.get('exploit','N/A')}
Vuln summary:    {json.dumps(vuln_summary)}
Confirmed exploitable vulnerabilities: {confirmed_count}

Write a comprehensive 4–5 paragraph executive summary:
1. **Engagement Overview & Scope**: Clearly define the target ({target}), in-scope assets (web application and supporting infrastructure), and out-of-scope assets (social engineering, physical security).
2. **Testing Methodology**: Explicitly state that the assessment followed industry standards including the OWASP Web Security Testing Guide (WSTG) and NIST SP 800-115.
3. **Overall Security Posture**: Be direct about the risk level.
4. **Key Findings**: Most critical findings in plain business language (no jargon), mentioning business impact.
5. **Authorization & Confidentiality Disclaimer**: End with a formal statement that testing was authorized and the report is strictly confidential.

Tone: highly professional, formal, authoritative, suitable for a CISO, Board of Directors, or compliance auditor.
Use markdown headers (###) for the subsections within the Executive Summary.

CRITICAL REPORTING CONSTRAINTS:
- You MUST align exactly with the numerical data. Do NOT contradict the "Vuln summary" data.
- If the Vuln summary lists CRITICAL findings (e.g., "CRITICAL": 1), you MUST NOT write that there are "no critical vulnerabilities".
- If confirmed_count is 0, state that findings are "detected weaknesses requiring manual verification", but do NOT pretend zero vulnerabilities were found if the summary counts are > 0."""
    return _llm_call(llm, prompt)


def section_attack_surface(llm: ChatGroq, recon: dict) -> str:
    subdomains = recon.get("subdomains", [])
    ports      = recon.get("open_ports", [])
    techs      = list(set(recon.get("technologies", [])))
    dns_a      = recon.get("dns_records", {}).get("A", [])
    emails     = list(set(recon.get("emails", [])))
    ssl        = recon.get("ssl_info", {})
    shodan     = recon.get("shodan_data", {})

    prompt = f"""You are writing the Attack Surface section of a pentest report.

Target: {recon.get('target','N/A')}

Recon data:
- IP addresses: {dns_a[:5]}
- Subdomains found: {len(subdomains)} — {_limit_data(subdomains, 15)}
- Open ports: {[_limit_data(p.get('port'), 10) for p in ports[:15]]}
- Services: {[_limit_data(p.get('service','') + ' ' + p.get('product',''), 20) for p in ports[:15] if p.get('service')]}
- Technologies: {_limit_data(techs, 15)}
- Emails found: {_limit_data(emails, 10)}
- SSL SANs: {_limit_data(ssl.get('sans', []), 10)}
- Shodan CVEs: {_limit_data(shodan.get('vulns', []), 10)}
- Organisation: {shodan.get('org','N/A')}

Write a structured attack surface overview formatted as a formal Asset Inventory.
Include:
1. **Infrastructure Assets**: IP addresses and related subdomains.
2. **Network Services**: Open ports and the specific services running on them.
3. **Technology Stack**: Technology versions and assumed patch levels based on the findings.
4. **Information Disclosure**: Emails, SSL certificate observations (e.g., SANs), and OSINT data from Shodan.

Use markdown with sub-headings (###) and bullet lists or tables where appropriate to present a professional asset inventory."""
    return _llm_call(llm, prompt)


def section_severity_table(vuln_summary: dict, vulns: list) -> str:
    """Build severity table as markdown — no LLM needed, pure data."""
    lines = [
        "## Vulnerability Severity Summary",
        "",
        "| Severity | Count | CVSS Range |",
        "|----------|-------|------------|",
    ]
    ranges = {"CRITICAL":"9.0–10.0","HIGH":"7.0–8.9","MEDIUM":"4.0–6.9","LOW":"0.1–3.9","INFO":"0.0"}
    for sev in ["CRITICAL","HIGH","MEDIUM","LOW","INFO"]:
        count = vuln_summary.get(sev, 0)
        if count:
            lines.append(f"| {sev} | {count} | {ranges[sev]} |")
    lines += ["", "### All findings", ""]
    lines.append("| # | Title | Severity | CVSS Score | CVSS Vector | Compliance | Target |")
    lines.append("|---|-------|----------|------------|-------------|------------|--------|")
    for i, v in enumerate(sorted(vulns, key=lambda x: -x.get("cvss_score",0)), 1):
        title    = v.get("title","")[:55]
        sev      = v.get("severity","INFO")
        score    = v.get("cvss_score", 0.0)
        cat      = v.get("category","")
        url      = v.get("target_url","")[:40]
        # Basic mapping placeholder, LLM fleshes it out in the other sections
        compliance = "ASVS v4.0 / NIST CSF"
        vector = "See details below"
        lines.append(f"| {i} | {title} | {sev} | {score} | {vector} | {compliance} | {url} |")
    return "\n".join(lines)


def section_critical_findings(llm: ChatGroq, vulns: list, exploit_results: list) -> str:
    critical_high = [v for v in vulns if v.get("severity") in ("CRITICAL","HIGH")]
    confirmed_map = {r.get("vuln_title",""):r for r in exploit_results if r.get("status")=="CONFIRMED"}

    prompt = f"""You are writing the Critical & High Findings section of a professional pentest report.

Findings:
{json.dumps(critical_high[:15], indent=2)}

Confirmed exploits:
{json.dumps(list(confirmed_map.values())[:10], indent=2)}

Write ## Critical & High Findings

For each finding write:
### [SEVERITY] Finding Title
- **CVSS v3.1 Score**: X.X
- **CVSS v3.1 Vector**: (Synthesize the likely CVSS v3.1 vector string, e.g., CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H)
- **Category**: (SQLi / XSS / etc.)
- **Compliance Mapping**: (Map to OWASP ASVS v4.0 requirement or NIST CSF category)
- **Affected URL**: ...
- **Description**: What the vulnerability is, how it works, and why it matters
- **Proof of Concept (PoC)**: Describe the sanitized request/response evidence or exact exploitation steps.
- **Exploitation Status**: CONFIRMED / DETECTED (not yet confirmed)
- **Business Impact**: Provide a formal business impact assessment (likelihood vs impact).
- **Remediation**: Concrete fix with actionable steps and code examples if relevant.
- **False Positive Analysis**: Explain why this is considered a true positive.

Mark confirmed exploits with ✅ CONFIRMED.
Be highly technical, rigorous, and specific."""
    return _llm_call(llm, prompt)


def section_medium_low(llm: ChatGroq, vulns: list) -> str:
    med_low = [v for v in vulns if v.get("severity") in ("MEDIUM","LOW","INFO")]
    if not med_low:
        return "## Medium, Low & Informational Findings\n\nNo medium/low findings recorded."

    prompt = f"""You are writing the Medium/Low/Informational findings section of a professional pentest report.

Findings:
{json.dumps(med_low[:20], indent=2)}

Write ## Medium, Low & Informational Findings

Use a compact but formal format — group by category where possible:
### [Category Name] (e.g., Missing Security Headers)
- **Finding**: X-Frame-Options Missing
- **CVSS v3.1 Vector**: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N
- **Compliance**: OWASP ASVS v4.0 ...
- **Risk**: Explanation of the theoretical risk.
- **Remediation**: Quick, actionable fix.

Keep each finding structured but concise (3-4 lines). Do not over-explain, as these are lower priority, but maintain professional rigor."""
    return _llm_call(llm, prompt)


def section_attack_chain(llm: ChatGroq, confirmed: list, vulns: list, target: str) -> str:
    if not confirmed:
        return ("## Attack Chain Analysis\n\n"
                "No vulnerabilities were confirmed exploitable in this engagement. "
                "The findings documented represent detected weaknesses requiring remediation "
                "before exploitation becomes possible.")

    prompt = f"""You are writing the Attack Chain section of a pentest report for {target}.

Confirmed exploitable vulnerabilities:
{json.dumps(confirmed, indent=2)}

All detected vulnerabilities (for context):
{json.dumps([v.get('title') for v in vulns], indent=2)}

Write ## Attack Chain Analysis

Describe the realistic kill chain a motivated attacker would follow:
1. Initial access — how they get in (which confirmed vuln)
2. Reconnaissance — what they learn from inside
3. Lateral movement / privilege escalation — where they go next
4. Impact — what they ultimately achieve (data theft, ransomware, etc.)

If multiple confirmed vulns exist, chain them together logically.
Use numbered steps. Be specific — name the actual vulnerabilities.
End with a one-sentence worst-case impact statement.

CRITICAL CONSTRAINT: ONLY mention vulnerabilities explicitly listed in the "All detected vulnerabilities" or "Confirmed exploitable vulnerabilities" lists above. DO NOT invent, assume, or hallucinate vulnerabilities, CVEs, or attack pathways that are not present in the provided data."""
    return _llm_call(llm, prompt)


def section_remediation_plan(llm: ChatGroq, vulns: list, confirmed: list) -> str:
    top_vulns = sorted(vulns, key=lambda x: -x.get("cvss_score",0))[:20]

    prompt = f"""You are writing the Remediation Plan section of a pentest report.

All vulnerabilities (sorted by CVSS):
{json.dumps([{"title":v.get("title"),"severity":v.get("severity"),
              "cvss":v.get("cvss_score"),"category":v.get("category"),
              "remediation":v.get("remediation")} for v in top_vulns], indent=2)}

Write ## Remediation Plan

### Immediate Actions (within 24–48 hours)
List CRITICAL findings that need urgent attention. For each:
- What to do
- Specific config change or code fix
- Estimated effort (hours)

### Short-term (within 2 weeks)
HIGH findings.

### Medium-term (within 30 days)
MEDIUM findings and security header improvements.

### Long-term / Process improvements
Structural fixes: WAF deployment, security training, DAST in CI/CD, etc.

End with a ## Remediation Priority Matrix table:
| Priority | Finding | Effort | Risk Reduction |
|----------|---------|--------|----------------|"""
    return _llm_call(llm, prompt)


def section_risk_rating(llm: ChatGroq, vuln_summary: dict,
                        confirmed_count: int, target: str) -> str:
    prompt = f"""You are writing the Overall Risk Rating section of a pentest report.

Target: {target}
Vulnerability summary: {json.dumps(vuln_summary)}
Confirmed exploitable vulnerabilities: {confirmed_count}

Write ## Overall Risk Rating

Give ONE overall rating: CRITICAL / HIGH / MEDIUM / LOW

Format:
## Overall Risk Rating

**Rating: [RATING]**

[3–4 sentences justifying the rating based on the specific findings.
Mention the most impactful confirmed vulnerability. Be direct.]

### Risk Breakdown
| Risk Factor | Assessment |
|-------------|------------|
| Likelihood of attack | HIGH / MEDIUM / LOW |
| Potential business impact | HIGH / MEDIUM / LOW |
| Data exposure risk | HIGH / MEDIUM / LOW |
| Ease of exploitation | EASY / MODERATE / DIFFICULT |
| Overall | [RATING] |"""
    return _llm_call(llm, prompt)


def section_backdoor_analysis(llm: ChatGroq, target: str, vulns: list) -> str:
    prompt = f"""You are writing the Backdoor & Compromise Assessment section of a professional pentest report for {target}.

Web-layer vulnerabilities detected:
{json.dumps([v.get('title') for v in vulns], indent=2)}

Write ## Backdoor & Compromise Assessment

Since we only performed external, web-layer heuristic testing, we must state that deep host-level backdoor scanning (like File Integrity Monitoring or Maldet) was NOT performed, but we did check for common web-layer indicators of compromise.

Include the following subsections:
### 1. Webshell & Malicious Endpoint Analysis
State whether any suspicious hidden paths, admin panels, or eval-based endpoints were discovered during directory enumeration that might indicate an existing webshell.

### 2. External Outbound Connection Risk
Assess the likelihood that a backdoor could establish outbound C2 (Command and Control) connections based on the current attack surface and firewall configuration implied by the open ports.

### 3. File Integrity Monitoring (FIM) Recommendations
Provide a strong recommendation to implement FIM (like AIDE, Tripwire, or osquery) and regular malware scanning (like ClamAV or Maldet) on the host to detect unauthorized modifications.

Tone: Professional, advisory, and clear about the limitations of external-only testing."""
    return _llm_call(llm, prompt)


# ══════════════════════════════════════════════════════════
#  HTML RENDERER
#  Wraps the markdown report in a clean self-contained HTML file
# ══════════════════════════════════════════════════════════

def render_html(target: str, markdown_content: str, vuln_summary: dict,
                confirmed_count: int, scan_date: str) -> str:
    crit  = vuln_summary.get("CRITICAL", 0)
    high  = vuln_summary.get("HIGH", 0)
    med   = vuln_summary.get("MEDIUM", 0)
    low   = vuln_summary.get("LOW", 0)
    total = sum(vuln_summary.values())

    # Full markdown → HTML conversion
    import re

    def inline_format(text: str) -> str:
        """Apply inline markdown formatting: bold, italic, inline code, links."""
        # Bold+italic combined: ***text***
        text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<strong><em>\1</em></strong>', text)
        # Bold: **text**
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
        # Italic: *text* or _text_
        text = re.sub(r'\*([^*\n]+?)\*', r'<em>\1</em>', text)
        text = re.sub(r'_([^_\n]+?)_', r'<em>\1</em>', text)
        # Inline code: `text`
        text = re.sub(r'`([^`]+?)`', r'<code>\1</code>', text)
        # Strikethrough: ~~text~~
        text = re.sub(r'~~(.+?)~~', r'<del>\1</del>', text)
        # Severity badges
        text = re.sub(r'\bCRITICAL\b', '<span class="badge crit">CRITICAL</span>', text)
        text = re.sub(r'\bHIGH\b', '<span class="badge high">HIGH</span>', text)
        text = re.sub(r'\bMEDIUM\b', '<span class="badge med">MEDIUM</span>', text)
        text = re.sub(r'\b(LOW)\b(?! risk)', '<span class="badge low">LOW</span>', text)
        return text

    def md_to_html(md: str) -> str:
        lines = md.split("\n")
        html = []
        in_table = False
        in_ul = False
        in_ol = False
        in_code_block = False
        code_lines = []

        def close_lists():
            nonlocal in_ul, in_ol
            if in_ul:
                html.append("</ul>")
                in_ul = False
            if in_ol:
                html.append("</ol>")
                in_ol = False

        def close_table():
            nonlocal in_table
            if in_table:
                html.append("</tbody></table>")
                in_table = False

        for line in lines:
            # Fenced code blocks
            if line.strip().startswith("```"):
                if in_code_block:
                    html.append("<pre><code>" + "\n".join(code_lines) + "</code></pre>")
                    code_lines = []
                    in_code_block = False
                else:
                    close_lists()
                    close_table()
                    in_code_block = True
                continue
            if in_code_block:
                code_lines.append(line)
                continue

            # Tables
            if line.startswith("|"):
                close_lists()
                if not in_table:
                    html.append('<table><thead>')
                    in_table = True
                    cells = [inline_format(c.strip()) for c in line.strip("|").split("|")]
                    html.append("<tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
                    html.append("</thead><tbody>")
                elif re.match(r"^\|[-| :]+\|$", line):
                    pass  # separator row — skip
                else:
                    cells = [inline_format(c.strip()) for c in line.strip("|").split("|")]
                    html.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
                continue
            else:
                close_table()

            # Horizontal rule
            if re.match(r'^---+$', line.strip()):
                close_lists()
                html.append("<hr>")
                continue

            # Headings
            if line.startswith("#### "):
                close_lists()
                html.append(f"<h4>{inline_format(line[5:])}</h4>")
            elif line.startswith("### "):
                close_lists()
                html.append(f"<h3>{inline_format(line[4:])}</h3>")
            elif line.startswith("## "):
                close_lists()
                html.append(f"<h2>{inline_format(line[3:])}</h2>")
            elif line.startswith("# "):
                close_lists()
                html.append(f"<h1>{inline_format(line[2:])}</h1>")
            # Blockquote
            elif line.startswith("> "):
                close_lists()
                html.append(f"<blockquote><p>{inline_format(line[2:])}</p></blockquote>")
            # Unordered list
            elif re.match(r"^[-*+] ", line):
                close_table()
                if in_ol:
                    html.append("</ol>")
                    in_ol = False
                if not in_ul:
                    html.append("<ul>")
                    in_ul = True
                content = inline_format(line[2:])
                html.append(f"<li>{content}</li>")
            # Ordered list
            elif re.match(r"^\d+\. ", line):
                close_table()
                if in_ul:
                    html.append("</ul>")
                    in_ul = False
                if not in_ol:
                    html.append("<ol>")
                    in_ol = True
                content = re.sub(r"^\d+\. ", "", line)
                html.append(f"<li>{inline_format(content)}</li>")
            # Empty line
            elif not line.strip():
                close_lists()
                html.append("<br>")
            # Normal paragraph
            else:
                close_lists()
                content = inline_format(line)
                html.append(f"<p>{content}</p>")

        close_table()
        close_lists()
        if in_code_block and code_lines:
            html.append("<pre><code>" + "\n".join(code_lines) + "</code></pre>")

        return "\n".join(html)

    body = md_to_html(markdown_content)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pentest Report — {target}</title>
<style>
  :root {{
    --bg: #0f1117; --surface: #1a1d27; --border: #2e3141;
    --text: #e2e4ef; --muted: #8b8fa8; --accent: #7c6af7;
    --crit: #ff4d4f; --high: #ff7a45; --med: #ffc53d; --low: #52c41a;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: 'Segoe UI', system-ui, sans-serif;
    background: var(--bg); color: var(--text);
    line-height: 1.7; font-size: 15px;
  }}
  .header {{
    background: var(--surface); border-bottom: 1px solid var(--border);
    padding: 32px 48px; display: flex; justify-content: space-between; align-items: center;
    position: relative;
  }}
  .header::before {{
    content: "CONFIDENTIAL & PROPRIETARY";
    position: absolute;
    top: 10px;
    right: 48px;
    font-size: 10px;
    letter-spacing: 2px;
    color: var(--crit);
    font-weight: 800;
  }}
  .header h1 {{ font-size: 22px; font-weight: 600; color: var(--text); }}
  .header .meta {{ color: var(--muted); font-size: 13px; text-align: right; }}
  .doc-control {{
    margin: 20px 48px; padding: 16px; background: var(--bg); border: 1px solid var(--border); border-radius: 6px;
    font-size: 12px;
  }}
  .doc-control table {{ margin: 0; }}
  .doc-control th {{ background: var(--surface); color: var(--muted); text-align: left; padding: 6px 12px; }}
  .doc-control td {{ padding: 6px 12px; }}
  .stats {{
    display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px;
    padding: 24px 48px; background: var(--surface);
    border-bottom: 1px solid var(--border);
  }}
  .stat-card {{
    background: var(--bg); border: 1px solid var(--border);
    border-radius: 10px; padding: 16px; text-align: center;
  }}
  .stat-card .num {{ font-size: 32px; font-weight: 700; }}
  .stat-card .label {{ font-size: 12px; color: var(--muted); margin-top: 4px; }}
  .stat-card.crit .num {{ color: var(--crit); }}
  .stat-card.high .num {{ color: var(--high); }}
  .stat-card.med  .num {{ color: var(--med);  }}
  .stat-card.low  .num {{ color: var(--low);  }}
  .content {{ max-width: 900px; margin: 0 auto; padding: 40px 48px; }}
  h1 {{ font-size: 22px; font-weight: 600; margin: 32px 0 12px; padding-bottom: 8px;
        border-bottom: 1px solid var(--border); color: var(--text); }}
  h2 {{ font-size: 18px; font-weight: 600; margin: 28px 0 10px; color: var(--accent); }}
  h3 {{ font-size: 15px; font-weight: 600; margin: 20px 0 8px; color: var(--text); }}
  h4 {{ font-size: 13px; font-weight: 600; margin: 16px 0 6px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }}
  p  {{ margin: 8px 0; color: var(--text); }}
  em {{ font-style: italic; color: inherit; }}
  del {{ color: var(--muted); text-decoration: line-through; }}
  strong {{ color: var(--text); font-weight: 600; }}
  hr {{ border: none; border-top: 1px solid var(--border); margin: 24px 0; }}
  ul, ol {{ padding-left: 24px; margin: 8px 0; }}
  li {{ margin: 4px 0; }}
  blockquote {{
    border-left: 3px solid var(--accent); margin: 12px 0;
    padding: 8px 16px; background: rgba(124,106,247,0.05); border-radius: 0 6px 6px 0;
  }}
  blockquote p {{ color: var(--muted); margin: 0; font-style: italic; }}
  code {{
    background: #252836; border: 1px solid var(--border);
    padding: 1px 6px; border-radius: 4px; font-family: 'Consolas', monospace;
    font-size: 13px; color: #a8d8ff;
  }}
  pre {{
    background: #1a1d27; border: 1px solid var(--border); border-radius: 6px;
    padding: 16px; overflow-x: auto; margin: 12px 0;
  }}
  pre code {{
    background: none; border: none; padding: 0; font-size: 13px; color: #a8d8ff;
    white-space: pre;
  }}
  table {{
    width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px;
  }}
  th {{
    background: var(--surface); color: var(--muted); text-align: left;
    padding: 10px 12px; border-bottom: 1px solid var(--border);
    font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px;
  }}
  td {{
    padding: 9px 12px; border-bottom: 1px solid var(--border); color: var(--text);
  }}
  tr:hover td {{ background: var(--surface); }}
  .badge {{
    display: inline-block; padding: 2px 8px; border-radius: 4px;
    font-size: 11px; font-weight: 700; letter-spacing: 0.5px;
  }}
  .badge.crit {{ background: #3d1515; color: var(--crit); }}
  .badge.high {{ background: #3d2010; color: var(--high); }}
  .badge.med  {{ background: #3d3010; color: var(--med);  }}
  .badge.low  {{ background: #0f2d10; color: var(--low);  }}
  .footer {{
    text-align: center; color: var(--muted); font-size: 12px;
    padding: 32px; border-top: 1px solid var(--border);
  }}
  strong {{ color: var(--text); font-weight: 600; }}
</style>
</head>
<body>

<div class="header">
  <h1>Professional Security Assessment</h1>
  <div class="meta">
    Target: {target}<br>
    Date: {scan_date}<br>
    Classification: CONFIDENTIAL
  </div>
</div>

<div class="doc-control">
  <table>
    <tr>
      <th>Version</th>
      <th>Date</th>
      <th>Author / Tester</th>
      <th>Status</th>
    </tr>
    <tr>
      <td>v1.0.0</td>
      <td>{scan_date}</td>
      <td>AI Security Agent (Grounded)</td>
      <td>FINAL REPORT</td>
    </tr>
    <tr>
      <td colspan="4" style="border-top: 1px solid var(--border); padding-top: 10px; color: var(--muted);">
        <strong>Tester Qualifications:</strong> Certified Ethical Hacker (CEH) Equivalent Logic Patterns, OWASP Top 10 Specialist Engine.
      </td>
    </tr>
  </table>
</div>

<div class="stats">
  <div class="stat-card crit">
    <div class="num">{crit}</div>
    <div class="label">Critical</div>
  </div>
  <div class="stat-card high">
    <div class="num">{high}</div>
    <div class="label">High</div>
  </div>
  <div class="stat-card med">
    <div class="num">{med}</div>
    <div class="label">Medium</div>
  </div>
  <div class="stat-card low">
    <div class="num">{low}</div>
    <div class="label">Low / Info</div>
  </div>
</div>

<div class="content">
{body}
</div>

<div class="footer">
  Pentest Agent — Autonomous Security Testing Pipeline &nbsp;|&nbsp;
  {total} findings &nbsp;|&nbsp; {confirmed_count} confirmed exploitable &nbsp;|&nbsp;
  {scan_date}
</div>

</body>
</html>"""


# ══════════════════════════════════════════════════════════
#  JSON SUMMARY BUILDER
#  Machine-readable summary for dashboards / MCP server
# ══════════════════════════════════════════════════════════

def build_json_summary(target: str, recon: dict, vulns_data: dict,
                       exploit_data: dict, scan_date: str) -> dict:
    vulns     = vulns_data.get("vulnerabilities", [])
    confirmed = [r for r in exploit_data.get("results", []) if r.get("status") == "CONFIRMED"]

    return {
        "report_metadata": {
            "target":       target,
            "generated_at": scan_date,
            "generator":    "pentest-agent/v1.0",
        },
        "scope": {
            "subdomains_found": len(recon.get("subdomains", [])),
            "open_ports":       [p.get("port") for p in recon.get("open_ports", [])],
            "technologies":     list(set(recon.get("technologies", []))),
            "ip_addresses":     recon.get("dns_records", {}).get("A", []),
        },
        "vulnerability_summary": vulns_data.get("summary", {}),
        "total_vulnerabilities": len(vulns),
        "confirmed_exploitable": len(confirmed),
        "top_vulnerabilities": [
            {
                "title":      v.get("title"),
                "severity":   v.get("severity"),
                "cvss_score": v.get("cvss_score"),
                "category":   v.get("category"),
                "target_url": v.get("target_url"),
                "remediation":v.get("remediation"),
            }
            for v in sorted(vulns, key=lambda x: -x.get("cvss_score", 0))[:10]
        ],
        "confirmed_exploits": [
            {
                "title":    r.get("vuln_title"),
                "category": r.get("vuln_category"),
                "technique":r.get("technique"),
                "impact":   r.get("impact"),
                "severity": r.get("severity"),
            }
            for r in confirmed
        ],
        "overall_risk": _compute_risk(vulns_data.get("summary", {}), len(confirmed)),
    }


def _compute_risk(summary: dict, confirmed: int) -> str:
    if summary.get("CRITICAL", 0) > 0 or confirmed > 0:
        return "CRITICAL"
    if summary.get("HIGH", 0) >= 3:
        return "HIGH"
    if summary.get("HIGH", 0) > 0 or summary.get("MEDIUM", 0) >= 5:
        return "MEDIUM"
    return "LOW"


# ══════════════════════════════════════════════════════════
#  MAIN REPORT ASSEMBLY
# ══════════════════════════════════════════════════════════

def run(recon: dict, vuln_data: dict, exploit_data: dict,
        model: str = GROQ_MODEL_DEFAULT) -> dict:
    """
    Entry point called by main.py.
    Accepts dicts from Parts 1, 2, 3.
    Returns dict with paths to all generated output files.
    """
    target    = recon.get("target", vuln_data.get("target", "unknown"))
    scan_date = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    vulns     = vuln_data.get("vulnerabilities", [])
    vuln_sum  = vuln_data.get("summary", {})
    if not isinstance(vuln_sum, dict):
        # Fallback if summary is a string (like strategic summary) or missing
        from agents.report_writer import _get_summary_counts
        vuln_sum = _get_summary_counts(vulns)
        
    results   = exploit_data.get("results", [])
    confirmed = [r for r in results if r.get("status") == "CONFIRMED"]

    scan_dates = {
        "recon":   recon.get("timestamp", "N/A")[:10],
        "vuln":    vuln_data.get("scan_start", "N/A")[:10],
        "exploit": exploit_data.get("session_start", "N/A")[:10],
    }

    console.print(Panel.fit(
        f"[bold green]Part 4 — Report Writer[/bold green]\n"
        f"[dim]Target: {target}  |  Model: {model}[/dim]",
        border_style="green"
    ))

    # Initialize LLM based on configured provider
    if LLM_PROVIDER == "gemini":
        primary_llm = ChatOpenAI(
            api_key=GEMINI_API_KEY,
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
            model=GEMINI_MODEL_DEFAULT,
            temperature=0.2
        )
        fallback_llm = ChatGroq(
            model=model,
            api_key=GROQ_API_KEY,
            temperature=0.2,
            max_tokens=4096
        )
        llm = primary_llm.with_fallbacks([fallback_llm])
        console.print(f"[dim]Using LLM: Gemini ({GEMINI_MODEL_DEFAULT}) with Groq Fallback[/dim]")
            
    else:  # groq default
        primary_llm = ChatGroq(
            model=model,
            api_key=GROQ_API_KEY,
            temperature=0.2,
            max_tokens=4096
        )
        # Use OpenAI-compatible endpoint for Gemini to avoid package conflicts
        fallback_llm = ChatOpenAI(
            api_key=GEMINI_API_KEY,
            base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
            model=GEMINI_MODEL_DEFAULT,
            temperature=0.2
        )
        llm = primary_llm.with_fallbacks([fallback_llm])
        console.print(f"[dim]Using LLM: Groq ({model}) with Gemini (OpenAI-mode) Fallback[/dim]")

    # ── Generate all 7 sections ───────────────────────────
    sections = {}

    console.print("\n[bold]Generating report sections...[/bold]")

    console.print("  [cyan]1/7[/cyan] Executive summary...")
    sections["executive_summary"] = section_executive_summary(
        llm, target, vuln_sum, len(confirmed), scan_dates)
    time.sleep(2)  # Delay to avoid rate limiting

    console.print("  [cyan]2/7[/cyan] Attack surface...")
    sections["attack_surface"] = section_attack_surface(llm, recon)
    time.sleep(2)

    console.print("  [cyan]3/7[/cyan] Severity table...")
    sections["severity_table"] = section_severity_table(vuln_sum, vulns)
    # No LLM call for severity table, but add delay before next LLM call
    time.sleep(2)

    console.print("  [cyan]4/7[/cyan] Critical & high findings...")
    sections["critical_findings"] = section_critical_findings(llm, vulns, results)
    time.sleep(2)

    console.print("  [cyan]5/7[/cyan] Medium & low findings...")
    sections["medium_low"] = section_medium_low(llm, vulns)
    time.sleep(2)

    console.print("  [cyan]6/7[/cyan] Attack chain analysis...")
    sections["attack_chain"] = section_attack_chain(llm, confirmed, vulns, target)
    time.sleep(2)

    console.print("  [cyan]7/8[/cyan] Remediation plan + risk rating...")
    sections["remediation"] = section_remediation_plan(llm, vulns, confirmed)
    time.sleep(1)
    sections["risk_rating"]  = section_risk_rating(llm, vuln_sum, len(confirmed), target)
    time.sleep(1)

    console.print("  [cyan]8/8[/cyan] Backdoor & compromise assessment...")
    sections["backdoor_analysis"] = section_backdoor_analysis(llm, target, vulns)

    # ── Assemble full markdown report ─────────────────────
    ts_safe = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    safe_t  = target.replace("/","_").replace(":","_").replace(".","_")

    full_markdown = f"""# Penetration Test Report — {target}

**Generated:** {scan_date}
**Classification:** CONFIDENTIAL
**Tool:** Pentest Agent v1.0

---

## Executive Summary

{sections['executive_summary']}

---

{sections['attack_surface']}

---

{sections['severity_table']}

---

{sections['critical_findings']}

---

{sections['medium_low']}

---

{sections['attack_chain']}

---

{sections['backdoor_analysis']}

---

{sections['remediation']}

---

{sections['risk_rating']}

---

*This report was generated autonomously by Pentest Agent.
All findings should be verified by a qualified security professional before remediation.*
"""

    # ── Save all output formats ───────────────────────────
    FINAL_DIR.mkdir(parents=True, exist_ok=True)

    md_path   = FINAL_DIR / f"report_{safe_t}_{ts_safe}.md"
    html_path = FINAL_DIR / f"report_{safe_t}_{ts_safe}.html"
    json_path = FINAL_DIR / f"report_{safe_t}_{ts_safe}.json"

    md_path.write_text(full_markdown, encoding="utf-8")
    console.print(f"\n[green]✓[/green] Markdown:  {md_path}")

    html_content = render_html(target, full_markdown, vuln_sum,
                               len(confirmed), scan_date)
    html_path.write_text(html_content, encoding="utf-8")
    console.print(f"[green]✓[/green] HTML:      {html_path}")

    json_summary = build_json_summary(target, recon, vuln_data, exploit_data, scan_date)
    json_path.write_text(json.dumps(json_summary, indent=2), encoding="utf-8")
    console.print(f"[green]✓[/green] JSON:      {json_path}")

    # ── Console preview ───────────────────────────────────
    console.print("\n" + "═" * 60)
    console.print(Panel(
        sections["executive_summary"],
        title=f"[bold green]Executive Summary — {target}[/bold green]",
        border_style="green",
    ))

    # Risk rating table
    overall_risk = json_summary["overall_risk"]
    risk_color   = {"CRITICAL":"bold red","HIGH":"red","MEDIUM":"yellow","LOW":"green"}.get(overall_risk,"white")
    table = Table(title="Final Risk Assessment", show_header=True)
    table.add_column("Category",  style="bold")
    table.add_column("Result")
    table.add_row("Target",                target)
    table.add_row("Total vulnerabilities", str(len(vulns)))
    table.add_row("Confirmed exploitable", str(len(confirmed)))
    table.add_row("Critical findings",     str(vuln_sum.get("CRITICAL",0)))
    table.add_row("High findings",         str(vuln_sum.get("HIGH",0)))
    table.add_row("Overall risk",          f"[{risk_color}]{overall_risk}[/{risk_color}]")
    console.print(table)

    return {
        "target":       target,
        "overall_risk": overall_risk,
        "md_path":      str(md_path),
        "html_path":    str(html_path),
        "json_path":    str(json_path),
        "summary":      json_summary,
    }


# ══════════════════════════════════════════════════════════
#  STANDALONE ENTRY
# ══════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Part 4 — Report writer")
    parser.add_argument("--recon",    required=True, help="Part 1 recon JSON path")
    parser.add_argument("--vulns",    required=True, help="Part 2 vuln JSON path")
    parser.add_argument("--exploits", required=True, help="Part 3 exploit JSON path")
    parser.add_argument("--model",    default=GROQ_MODEL_DEFAULT,
                        choices=list(GROQ_MODELS.keys()))
    args = parser.parse_args()

    run(
        recon        = load_json(args.recon),
        vuln_data    = load_json(args.vulns),
        exploit_data = load_json(args.exploits),
        model        = args.model,
    )
def add_legal_disclaimer(report: str) -> str:
    """Add legal disclaimer to all reports"""
    disclaimer = """
## ⚠️ LEGAL DISCLAIMER

This report was generated by an automated AI-powered security tool.

**IMPORTANT**:
- All findings MUST be manually verified before any action
- CVEs should be verified against NVD database
- False positives are common with automated tools
- This report does NOT replace professional penetration testing
- Do NOT submit unverified findings to companies
- Only use on systems you own or have written permission to test

**Confidence Levels**:
- 🔴 LOW = AI-generated, requires verification
- 🟡 MEDIUM = Automated check passed, manual review recommended  
- 🟢 HIGH = Manually verified with evidence

*Generated by Pentest Agent v1.0 | {datetime.utcnow().isoformat()}*
"""
    return report + disclaimer