/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AnalyzeResultSourceBreakdown } from "./analyzeResultSourceBreakdown";
import type { ExtractedTask } from "./extractedTask";

export interface AnalyzeResult {
  summary: string;
  tasks: ExtractedTask[];
  weeklyPlan: string;
  missedItems: string[];
  urgentItems: string[];
  sourceBreakdown: AnalyzeResultSourceBreakdown;
}
