/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */

export interface AnalyzeInput {
  /** The raw course content to analyze */
  text: string;
  /** The source platform (brightspace, discord, googledrive, quiz, feedback) */
  source: string;
  /**
   * Optional additional course context
   * @nullable
   */
  courseContext?: string | null;
}
