/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Analyzes pasted course content and extracts tasks, deadlines, and summaries
 * @summary Analyze course text
 */
export const AnalyzeCourseBody = zod.object({
  text: zod.string().describe("The raw course content to analyze"),
  source: zod
    .string()
    .describe(
      "The source platform (brightspace, discord, googledrive, quiz, feedback)",
    ),
  courseContext: zod
    .string()
    .nullish()
    .describe("Optional additional course context"),
});

export const AnalyzeCourseResponse = zod.object({
  summary: zod.string(),
  tasks: zod.array(
    zod.object({
      id: zod.string(),
      title: zod.string(),
      source: zod.string(),
      dueDate: zod.string().nullish(),
      priority: zod.enum(["high", "medium", "low"]),
      status: zod.enum(["pending", "completed", "overdue"]),
      explanation: zod.string(),
      confidenceScore: zod.number(),
    }),
  ),
  weeklyPlan: zod.string(),
  missedItems: zod.array(zod.string()),
  urgentItems: zod.array(zod.string()),
  sourceBreakdown: zod.record(zod.string(), zod.number()),
});

/**
 * Ask questions about course data and get AI-powered answers
 * @summary Chat with AI assistant
 */
export const ChatAssistantBody = zod.object({
  message: zod.string(),
  courseContext: zod
    .string()
    .nullish()
    .describe("Serialized course data for context"),
});

export const ChatAssistantResponse = zod.object({
  reply: zod.string(),
  isDemo: zod.boolean(),
});

/**
 * Converts rough peer feedback notes into a polished, structured review
 * @summary Polish peer feedback
 */
export const PolishFeedbackBody = zod.object({
  presenterName: zod.string(),
  projectTitle: zod.string(),
  bestPart: zod.string(),
  improvement: zod.string(),
  clarityRating: zod.number(),
  demoQualityRating: zod.number(),
  usefulnessRating: zod.number(),
  notes: zod.string().nullish(),
});

export const PolishFeedbackResponse = zod.object({
  bestPart: zod.string(),
  improvementSuggestion: zod.string(),
  overallFeedback: zod.string(),
  isDemo: zod.boolean(),
});
