/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */

export type ExtractedTaskStatus =
  (typeof ExtractedTaskStatus)[keyof typeof ExtractedTaskStatus];

export const ExtractedTaskStatus = {
  pending: "pending",
  completed: "completed",
  overdue: "overdue",
} as const;
