/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */
import type { ExtractedTaskPriority } from "./extractedTaskPriority";
import type { ExtractedTaskStatus } from "./extractedTaskStatus";

export interface ExtractedTask {
  id: string;
  title: string;
  source: string;
  /** @nullable */
  dueDate?: string | null;
  priority: ExtractedTaskPriority;
  status: ExtractedTaskStatus;
  explanation: string;
  confidenceScore: number;
}
