/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */

export type ExtractedTaskPriority =
  (typeof ExtractedTaskPriority)[keyof typeof ExtractedTaskPriority];

export const ExtractedTaskPriority = {
  high: "high",
  medium: "medium",
  low: "low",
} as const;
