/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * UniFlow API specification
 * OpenAPI spec version: 0.1.0
 */

export interface FeedbackInput {
  presenterName: string;
  projectTitle: string;
  bestPart: string;
  improvement: string;
  clarityRating: number;
  demoQualityRating: number;
  usefulnessRating: number;
  /** @nullable */
  notes?: string | null;
}
